spring:
  application:
    name: hrm-eureka #服务名称
server:
  port: 7001 # 端口号
eureka:
  instance:
    hostname: localhost #  eureka  ip
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置
